"use client";

import { useMemo, useState, type CSSProperties } from "react";
import { AREA_META, DEFAULT_SETTINGS, analyzeChip, formatNumber, type AreaType, type Cell, type CellSettings, type Tool } from "../lib/chip-analysis";
import { makeId, type SavedComponent } from "../lib/component-model";
import { LITHOGRAPHY_TIERS, availableTransistors, nodeLabel, tierById, type LithographyTierId } from "../lib/lithography";
import { initialValues, type DesignerConfig } from "./component-config";

const RADAR_AXES=["Scalar","Dense Matrix","Graph/Network","Discrete Logic","Continuous Stream","Spatial Trees","Vector Embeddings","Probabilistic"];
const AFFINITY:Record<string,number[]>={"ALU Cores":[3,0,1,1,1,1,0,1],"SIMD Cores":[0,3,0,0,3,0,1,1],"Systolic Array":[0,3,0,0,0,0,1,0],"RT Cores":[0,0,0,0,0,3,0,0],"Graph Streaming Processor":[0,0,3,0,0,0,1,0],"FPGA Fabric":[0,0,0,3,0,0,0,0],"Photonic Processor":[0,3,0,0,3,0,0,0],"Vector Search Accelerator":[0,0,0,0,0,0,3,0],NPU:[0,3,0,0,0,0,3,0],"Neuromorphic Processor":[0,0,0,0,0,0,0,3],"Storage Controller":[0,0,0,0,0,3,0,0]};

function OptionStep({title,copy,fields,back,next}:{title:string;copy:string;fields:Array<{label:string;value:string;set:(value:string)=>void;options:string[]}>;back:()=>void;next:()=>void}) {
  return <div className="workflow-narrow"><div className="workflow-title"><p className="eyebrow">CONFIGURATION</p><h2>{title}</h2><p>{copy}</p></div><section className="form-panel">{fields.map(field=><label key={field.label}><span>{field.label}</span><select value={field.value} onChange={e=>field.set(e.target.value)}>{field.options.map(value=><option key={value}>{value}</option>)}</select></label>)}</section><div className="workflow-actions split"><button className="button ghost" onClick={back}>← Back</button><button className="button primary" onClick={next}>Continue →</button></div></div>;
}

function CpuToolOptions({ tool, settings, tierId, change }: { tool:Tool; settings:Record<AreaType,CellSettings>; tierId:LithographyTierId; change:(patch:CellSettings)=>void }) {
  if(tool==="erase") return <div className="tool-options"><p className="panel-label">ERASER</p><p>Click occupied cells to clear them.</p></div>;
  const active=settings[tool], tier=tierById(tierId);
  return <div className="tool-options"><p className="panel-label">CONSTRUCTION OPTIONS</p><div className="option-heading"><span style={{background:AREA_META[tool].color}}/><div><h3>{AREA_META[tool].label}</h3><p>{AREA_META[tool].description}</p></div></div>{tool==="alu"&&<><label><span>Transistor type</span><select value={active.transistor} onChange={e=>change({transistor:e.target.value as CellSettings["transistor"]})}>{availableTransistors(tierId).map(value=><option key={value}>{value}</option>)}</select></label><NodeSelect value={active.transistorSize} nodes={tier.nodes} change={value=>change({transistorSize:value})}/><label><span>Core tier</span><select value={active.tier} onChange={e=>change({tier:e.target.value as CellSettings["tier"]})}><option>Performance</option><option>Efficiency</option></select></label><label><span>Power delivery</span><select value={active.deliveryLocation} onChange={e=>change({deliveryLocation:e.target.value as CellSettings["deliveryLocation"]})}><option>Front-side</option><option>Backside</option></select></label></>}{(tool==="l2"||tool==="l3")&&<><label><span>Cell topology</span><select value={active.cacheTopology} onChange={e=>change({cacheTopology:e.target.value as CellSettings["cacheTopology"]})}><option>6T</option><option>8T</option><option>10T</option></select></label><NodeSelect value={active.transistorSize} nodes={tier.nodes} change={value=>change({transistorSize:value})}/></>}{tool==="power"&&<label><span>Delivery quality</span><select value={active.quality} onChange={e=>change({quality:Number(e.target.value)})}><option value="1">Basic</option><option value="2">Standard</option><option value="3">Premium</option></select></label>}{tool==="io"&&<label><span>Interface</span><select value={active.interfaceType} onChange={e=>change({interfaceType:e.target.value as CellSettings["interfaceType"]})}><option>Standard</option><option>High-Bandwidth</option></select></label>}{tool==="igpu"&&<label><span>Compute quality</span><select value={active.quality} onChange={e=>change({quality:Number(e.target.value)})}><option value="1">Economy</option><option value="2">Standard</option><option value="3">Dense</option></select></label>}</div>;
}

function NodeSelect({value,nodes,change}:{value:CellSettings["transistorSize"];nodes:Array<number|"sub-2">;change:(value:number|"sub-2")=>void}) {
  return <label><span>Transistor size</span><select value={String(value)} onChange={e=>change(e.target.value==="sub-2"?"sub-2":Number(e.target.value))}>{nodes.map(node=><option key={String(node)} value={String(node)}>{nodeLabel(node)}</option>)}</select></label>;
}

export function CpuDesigner({ saved, save, exit }: { saved:SavedComponent[]; save:(item:SavedComponent)=>void; exit:()=>void }) {
  const [step,setStep]=useState(0), [tierId,setTierId]=useState<LithographyTierId>("stepper");
  const tier=tierById(tierId);
  const makeSettings=(id:LithographyTierId)=>Object.fromEntries((Object.keys(DEFAULT_SETTINGS) as AreaType[]).map(type=>[type,{...DEFAULT_SETTINGS[type],transistorSize:tierById(id).nodes[0],...(type==="alu"?{transistor:availableTransistors(id)[0]}:{})}])) as Record<AreaType,CellSettings>;
  const [cells,setCells]=useState<Array<Cell|null>>(()=>Array(tier.gridWidth*tier.gridHeight).fill(null));
  const [tool,setTool]=useState<Tool>("alu"), [settings,setSettings]=useState(()=>makeSettings(tierId));
  const [layout,setLayout]=useState("LGA"), [size,setSize]=useState("Standard"), [material,setMaterial]=useState("Copper"), [thermal,setThermal]=useState("Solder"), [name,setName]=useState(""), [notice,setNotice]=useState("");
  const analysis=useMemo(()=>analyzeChip(cells,tier.gridWidth,tier.gridHeight),[cells,tier]);
  const changeTier=(id:LithographyTierId)=>{const next=tierById(id);setTierId(id);setCells(Array(next.gridWidth*next.gridHeight).fill(null));setSettings(makeSettings(id));setStep(0)};
  const paint=(index:number)=>setCells(previous=>{const next=[...previous];next[index]=tool==="erase"?null:{type:tool,settings:{...settings[tool]}};return next});
  const change=(patch:CellSettings)=>{if(tool!=="erase")setSettings(previous=>({...previous,[tool]:{...previous[tool],...patch}}))};
  const load=(item:SavedComponent)=>{if(!item.die)return;setTierId(item.die.lithographyTier);setCells(item.die.cells);setSettings(makeSettings(item.die.lithographyTier));setName(`${item.name} revision`);setStep(1)};
  const finish=()=>{save({id:makeId("cpu"),name:name.trim(),type:"CPU",createdAt:Date.now(),stats:{Cores:analysis.cores.length,"L2 MB":Number(analysis.totalL2.toFixed(1)),"L3 MB":Number(analysis.totalL3.toFixed(1)),Heat:Number(analysis.heat.toFixed(1)),"I/O":analysis.ioThroughput,Lithography:tier.name,"Die Size":`${tier.width} × ${tier.height} mm`,Utilization:`${Math.round(analysis.usedPixels/cells.length*100)}%`},compatibility:{cpuLayout:layout},die:{lithographyTier:tierId,width:tier.width,height:tier.height,gridWidth:tier.gridWidth,gridHeight:tier.gridHeight,cells}});setNotice("Saved to Components and made available to Production.")};
  const labels=["Process","Floorplan","Package","Thermal","Finalize"];
  return <main className="designer-page"><div className="designer-header"><div><p className="eyebrow">COMPONENT DESIGN / CPU</p><h1>Central Processing Unit</h1></div><span>{tier.name}</span></div><ol className="stepper">{labels.map((label,index)=><li key={label} className={step===index?"current":step>index?"complete":""}><button onClick={()=>setStep(index)}><span>{String(index+1).padStart(2,"0")}</span>{label}</button></li>)}</ol><div className="workflow-body">
    {step===0&&<><div className="workflow-narrow"><div className="workflow-title"><p className="eyebrow">STEP 01 / PROCESS TARGET</p><h2>Design for which lithography line?</h2><p>The process target directly sets canvas dimensions and available construction choices. Changing it resets the floorplan.</p></div><div className="process-layout"><section className="form-panel"><label><span>Lithography tier</span><select value={tierId} onChange={e=>changeTier(e.target.value as LithographyTierId)}>{LITHOGRAPHY_TIERS.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="process-readout"><strong>{tier.width} × {tier.height} mm</strong><span>{tier.gridWidth} × {tier.gridHeight} editable cells</span><span>Nodes: {tier.nodes.map(nodeLabel).join(", ")}</span><span>Transistors: {availableTransistors(tier.id).join(", ")}</span></div></section><aside className="saved-inline"><p className="panel-label">PICK FROM SAVED DIES</p>{saved.filter(item=>item.type==="CPU"&&item.die).map(item=><button key={item.id} onClick={()=>load(item)}><strong>{item.name}</strong><span>{item.die?.width} × {item.die?.height} mm</span></button>)}</aside></div></div><div className="workflow-actions workflow-narrow"><button className="button primary" onClick={()=>setStep(1)}>Open floorplan →</button></div></>}
    {step===1&&<div className="editor-shell"><div className="editor-topline"><div><p className="eyebrow">MONOLITHIC IC FLOORPLANNER</p><h2>{tier.width} × {tier.height} mm canvas</h2></div><button className="text-button danger" onClick={()=>setCells(Array(cells.length).fill(null))}>Clear grid</button></div><div className="editor-layout"><aside className="palette-panel"><p className="panel-label">AREA PALETTE</p><div className="tool-list">{(Object.keys(AREA_META) as AreaType[]).map((type,index)=><button key={type} className={tool===type?"active":""} onClick={()=>setTool(type)}><span className="tool-key">{index+1}</span><i style={{background:AREA_META[type].color}}/><span><strong>{AREA_META[type].label}</strong><small>{analysis.counts[type]} CELLS</small></span></button>)}<button className={tool==="erase"?"active eraser":"eraser"} onClick={()=>setTool("erase")}><span className="tool-key">8</span><i>×</i><span><strong>Eraser</strong><small>CLEAR</small></span></button></div></aside><section className="canvas-column"><div className="die-scroll"><div className="die-frame"><div className="die-grid" style={{"--die-columns":tier.gridWidth,"--die-ratio":`${tier.width} / ${tier.height}`,"--die-max-width":`${tier.gridWidth*25}px`,"--die-min-width":`${tier.gridWidth*13}px`} as CSSProperties}>{cells.map((cell,index)=><button key={index} className={cell?"painted":""} style={cell?{"--cell-color":AREA_META[cell.type].color} as CSSProperties:undefined} onClick={()=>paint(index)} title={cell?AREA_META[cell.type].label:"Unassigned"}>{cell&&<span>{AREA_META[cell.type].short}</span>}</button>)}</div></div></div><CpuToolOptions tool={tool} settings={settings} tierId={tierId} change={change}/></section><aside className="stats-panel"><div className="stats-title"><div><p className="panel-label">LIVE ANALYSIS</p><h3>Die telemetry</h3></div></div><div className="primary-stats"><div><span>CORES</span><strong>{analysis.cores.length}</strong></div><div><span>UTILIZATION</span><strong>{Math.round(analysis.usedPixels/cells.length*100)}%</strong></div><div><span>HEAT</span><strong>{formatNumber(analysis.heat)}</strong></div><div><span>I/O</span><strong>{analysis.ioThroughput}</strong></div></div><div className="cache-stats"><div><span>L2</span><strong>{formatNumber(analysis.totalL2)} MB</strong></div><div><span>L3</span><strong>{formatNumber(analysis.totalL3)} MB</strong></div></div>{analysis.warnings.length>0&&<div className="warning-list">{analysis.warnings.map(warning=><div key={warning}><span>!</span><p>{warning}</p></div>)}</div>}</aside></div><div className="workflow-actions split"><button className="button ghost" onClick={()=>setStep(0)}>← Process</button><button className="button primary" disabled={!analysis.cores.length} onClick={()=>setStep(2)}>Package →</button></div></div>}
    {step===2&&<OptionStep title="Package configuration" copy="Layout is the CPU-to-motherboard compatibility key." fields={[{label:"Package Layout",value:layout,set:setLayout,options:["LGA","PGA","BGA"]},{label:"Package Size",value:size,set:setSize,options:["Compact","Standard","Large"]}]} back={()=>setStep(1)} next={()=>setStep(3)}/>} 
    {step===3&&<OptionStep title="Heat spreader" copy="Choose the external material and die-to-spreader thermal interface." fields={[{label:"Material",value:material,set:setMaterial,options:["Aluminum","Copper","Vapor Chamber"]},{label:"Thermal Interface",value:thermal,set:setThermal,options:["Thermal Paste","Solder","Direct-Die"]}]} back={()=>setStep(2)} next={()=>setStep(4)}/>} 
    {step===4&&<div className="finalize-shell"><div className="finalize-title"><p className="eyebrow">DESIGN REVIEW</p><h2>{name||"Unnamed CPU"}</h2><p>The die construction record is saved so Production can recompute yield against any compatible Fab Line.</p></div><section className="review-panel"><label className="name-control"><span>NAME THIS PART</span><input value={name} maxLength={36} onChange={e=>setName(e.target.value)} placeholder="CPU designation"/></label><div className="summary-stats"><div><span>CORES</span><strong>{analysis.cores.length}</strong></div><div><span>L2</span><strong>{formatNumber(analysis.totalL2)}</strong></div><div><span>DIE</span><strong>{tier.width}×{tier.height}</strong></div><div><span>PROCESS</span><strong>{tier.nodes.map(nodeLabel).join("/")}</strong></div></div><dl className="review-list"><div><dt>Lithography</dt><dd>{tier.name}</dd></div><div><dt>Package</dt><dd>{layout} / {size}</dd></div><div><dt>Thermal</dt><dd>{material} / {thermal}</dd></div></dl>{notice&&<p className="success-banner">✓ {notice}</p>}</section><div className="final-actions"><button className="button ghost" onClick={()=>setStep(3)}>← Thermal</button><div><button className="button secondary" onClick={()=>setStep(1)}>Keep Working</button><button className="button primary" disabled={!name.trim()||!analysis.cores.length} onClick={finish}>Save</button><button className="button primary exit-button" onClick={exit}>Exit</button></div></div></div>}
  </div></main>;
}

function MiniIc({areas,counts,onCounts}:{areas:string[];counts:Record<string,number>;onCounts:(next:Record<string,number>)=>void}) {
  const [active,setActive]=useState(areas[0]);
  const cells=Array.from({length:60},(_,index)=>areas.find(area=>index<areas.slice(0,areas.indexOf(area)+1).reduce((sum,item)=>sum+(counts[item]||0),0))||"");
  const paint=(index:number)=>{const old=cells[index],next={...counts};if(old)next[old]=Math.max(0,(next[old]||0)-1);next[active]=(next[active]||0)+1;onCounts(next)};
  return <section className="mini-ic"><div className="mini-palette">{areas.map((area,index)=><button key={area} className={active===area?"active":""} onClick={()=>setActive(area)}><i style={{background:`hsl(${(index*43+205)%360} 55% 55%)`}}/>{area}<small>{counts[area]||0}</small></button>)}</div><div className="mini-grid">{cells.map((area,index)=><button key={index} title={area||"Unassigned"} style={area?{background:`hsl(${(areas.indexOf(area)*43+205)%360} 55% 55%)`}:undefined} onClick={()=>paint(index)}/>)}</div></section>;
}

function Radar({counts}:{counts:Record<string,number>}) {
  const values=RADAR_AXES.map((_,axis)=>Object.entries(counts).reduce((sum,[area,count])=>sum+count*(AFFINITY[area]?.[axis]||0),0)), max=Math.max(1,...values);
  const points=values.map((value,index)=>{const angle=-Math.PI/2+index*Math.PI/4,radius=42*value/max;return `${50+Math.cos(angle)*radius},${50+Math.sin(angle)*radius}`}).join(" ");
  return <div className="radar-wrap"><svg viewBox="0 0 100 100" role="img" aria-label="Problem structure radar"><polygon points="50,7 80,20 93,50 80,80 50,93 20,80 7,50 20,20" className="radar-grid"/><polygon points={points} className="radar-shape"/></svg><div className="radar-legend">{RADAR_AXES.map((axis,index)=><span key={axis}><i style={{width:`${Math.max(3,values[index]/max*100)}%`}}/>{axis}: {values[index]}</span>)}</div></div>;
}

export function GenericDesigner({config,save,exit}:{config:DesignerConfig;save:(item:SavedComponent)=>void;exit:()=>void}) {
  const [values,setValues]=useState<Record<string,string>>(()=>initialValues(config)), [counts,setCounts]=useState<Record<string,number>>(()=>Object.fromEntries((config.icAreas||[]).map(area=>[area,0]))), [name,setName]=useState(""), [saved,setSaved]=useState(false);
  const submit=()=>{const compatibility:SavedComponent["compatibility"]={};if(config.type==="Expansion Card"||config.type==="NIC")compatibility.busInterface=values["Bus Interface"];if(config.type==="Motherboard"){compatibility.cpuSocket=values["CPU Socket"];compatibility.motherboardFormFactor=values["Form Factor"];compatibility.expansionSlots=Array(Number(values["Expansion Slots"]||1)).fill(values["Expansion Slot Type"])}if(config.type==="Case")compatibility.caseFormFactor=values["Form Factor"];save({id:makeId(config.code.toLowerCase()),name:name.trim(),type:config.type,createdAt:Date.now(),stats:{...values,...Object.fromEntries(Object.entries(counts).map(([key,value])=>[`${key} cells`,value]))},compatibility});setSaved(true)};
  return <main className="designer-page"><div className="designer-header"><div><p className="eyebrow">COMPONENT DESIGN / {config.code}</p><h1>{config.type}</h1></div><span>FUNCTIONAL DESIGN ROUTE</span></div><div className="workflow-body"><div className="workflow-narrow"><div className="workflow-title"><p className="eyebrow">DESIGN & FINALIZE</p><h2>{config.summary}</h2><p>Configure the component, name it, and save it for the library and Rig Builder.</p></div>{config.icAreas&&<><p className="panel-label">IC FLOORPLAN / 10 × 6 CELLS</p><MiniIc areas={config.icAreas} counts={counts} onCounts={setCounts}/>{config.type==="Expansion Card"&&<><p className="panel-label radar-title">PROBLEM STRUCTURE READOUT</p><Radar counts={counts}/></>}</>}<section className="form-panel option-grid">{config.fields.map(field=><label key={field.key}><span>{field.label}</span><select value={values[field.key]} onChange={e=>setValues(previous=>({...previous,[field.key]:e.target.value}))}>{field.values.map(value=><option key={value}>{value}</option>)}</select></label>)}<label className="name-control"><span>NAME THIS PART</span><input value={name} onChange={e=>setName(e.target.value)} maxLength={36} placeholder={`${config.type} designation`}/></label></section>{saved&&<p className="success-banner">✓ Saved. This part is now available in the component library and Rig Builder.</p>}<div className="workflow-actions split"><button className="button ghost" onClick={exit}>← Exit</button><div><button className="button secondary" onClick={()=>setSaved(false)}>Keep Working</button><button className="button primary" disabled={!name.trim()||(Boolean(config.icAreas)&&Object.values(counts).every(value=>value===0))} onClick={submit}>Save Component</button></div></div></div></div></main>;
}
