"use client";

import { useState } from "react";
import { FAB_STAGES, analyzeFabRun, type FabLine, type QcType, type TestTier } from "../lib/fab-line";
import { makeId, type SavedComponent } from "../lib/component-model";
import { LITHOGRAPHY_TIERS, tierById, type LithographyTierId } from "../lib/lithography";
import { Heading, type Screen } from "./system-pages";

const percent = (value:number)=>`${(value*100).toFixed(1)}%`;

export function ProductionHub({go}:{go:(screen:Screen)=>void}) {
  const cards:Array<[Screen,string,string,string]>=[["fab-design","01","Design New Fab Line","Choose exposure, test equipment, Room Air Quality, and seven optional QC checkpoints."],["fab-saved","02","Saved Fab Lines","Inspect persistent production-line configurations."],["fab-run","03","Run a Fab Line","Check compatibility, yield, binning, and expected material use."]];
  return <main className="page-shell"><Heading eyebrow="PRODUCTION / SEMICONDUCTOR" title="Fab Line Control" copy="Create a linear eight-stage fabrication line, store it, then analyze saved CPU dies against its process capability."/><section className="hub-grid">{cards.map(([screen,index,title,copy],i)=><button key={screen} className={`hub-card ${i===0?"primary-card":""}`} onClick={()=>go(screen)}><span className="card-index">{index}</span><span className="hub-icon">{i===0?"＋":i===1?"▦":"▶"}</span><span className="hub-card-content"><strong>{title}</strong><span>{copy}</span></span><span className="card-arrow">→</span></button>)}</section></main>;
}

export function FabDesigner({save,exit}:{save:(line:FabLine)=>void;exit:()=>void}) {
  const [name,setName]=useState(""), [lithography,setLithography]=useState<LithographyTierId>("stepper"), [testTier,setTestTier]=useState<TestTier>("Basic"), [air,setAir]=useState(85), [qc,setQc]=useState<QcType[]>(Array(7).fill("None")), [done,setDone]=useState(false);
  const submit=()=>{save({id:makeId("fab"),name:name.trim(),createdAt:Date.now(),lithographyTier:lithography,testTier,airQuality:air,checkpoints:qc});setDone(true)};
  return <main className="page-shell"><Heading eyebrow="PRODUCTION / NEW LINE" title="Design a Fab Line" copy="The line is intentionally linear—eight configured process stages, with optional inspection between each pair."/><section className="fab-config"><label><span>FAB LINE NAME</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Line designation"/></label><label><span>ROOM AIR QUALITY <output>{air}/100</output></span><input type="range" min="0" max="100" value={air} onChange={e=>setAir(Number(e.target.value))}/></label></section><section className="fab-line">{FAB_STAGES.map((stage,index)=><div className="fab-node-wrap" key={stage.id}><article className="fab-stage"><span>{String(index+1).padStart(2,"0")}</span><h3>{stage.name}</h3><p>{stage.material}</p>{stage.id==="exposure"&&<label><span>Litho Technology</span><select value={lithography} onChange={e=>setLithography(e.target.value as LithographyTierId)}>{LITHOGRAPHY_TIERS.map(tier=><option key={tier.id} value={tier.id}>{tier.name}</option>)}</select></label>}{stage.id==="probe"&&<label><span>Test Equipment</span><select value={testTier} onChange={e=>setTestTier(e.target.value as TestTier)}><option>Basic</option><option>Advanced (Binning)</option></select></label>}</article>{index<7&&<div className={`qc-node ${qc[index]!=="None"?"active":""}`}><span>QC {index+1}</span><select value={qc[index]} onChange={e=>setQc(previous=>previous.map((value,i)=>i===index?e.target.value as QcType:value))}><option>None</option><option>Manual</option><option>Automated</option></select><small>{qc[index]==="Manual"?"60% catch / 40% rework":qc[index]==="Automated"?"90% catch / 65% rework":"No early inspection"}</small></div>}</div>)}</section>{done&&<p className="success-banner">✓ Fab Line saved and ready to run.</p>}<div className="workflow-actions split"><button className="button ghost" onClick={exit}>← Production</button><button className="button primary" disabled={!name.trim()} onClick={submit}>Save Fab Line</button></div></main>;
}

export function SavedFabs({lines}:{lines:FabLine[]}) {
  return <main className="page-shell"><Heading eyebrow="PRODUCTION / LIBRARY" title="Saved Fab Lines" copy="Every line retains its exposure capability, test equipment, Room Air Quality, and QC sequence."/><section className="saved-grid">{lines.map(line=><article key={line.id}><span className="type-pill">FAB LINE</span><h3>{line.name}</h3><dl><div><dt>Lithography</dt><dd>{tierById(line.lithographyTier).name}</dd></div><div><dt>Test</dt><dd>{line.testTier}</dd></div><div><dt>Air Quality</dt><dd>{line.airQuality}/100</dd></div><div><dt>QC</dt><dd>{line.checkpoints.filter(value=>value!=="None").length}/7 active</dd></div></dl></article>)}{!lines.length&&<div className="empty-state"><strong>NO FAB LINES</strong><p>Design and save a Fab Line first.</p></div>}</section></main>;
}

export function FabRun({components,lines}:{components:SavedComponent[];lines:FabLine[]}) {
  const dies=components.filter(item=>item.type==="CPU"&&item.die), [dieId,setDieId]=useState(""), [lineId,setLineId]=useState("");
  const die=dies.find(item=>item.id===dieId), line=lines.find(item=>item.id===lineId);
  const result=die&&line?analyzeFabRun(die,line):null;
  return <main className="page-shell"><Heading eyebrow="PRODUCTION / RUN ANALYSIS" title="Run a Fab Line" copy="Select one saved CPU die and one saved line. Results are deterministic expected percentages averaged over repeated one-die runs."/><section className="run-selectors"><label><span>SAVED DIE</span><select value={dieId} onChange={e=>setDieId(e.target.value)}><option value="">Select a CPU die</option>{dies.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>SAVED FAB LINE</span><select value={lineId} onChange={e=>setLineId(e.target.value)}><option value="">Select a Fab Line</option>{lines.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></section>{!dies.length&&<p className="info-banner">Save a CPU die before running Production.</p>}{!lines.length&&<p className="info-banner">Save a Fab Line before running Production.</p>}{result&&<><div className={`compat-banner ${result.compatible?"pass":"fail"}`}><strong>{result.compatible?"✓ PROCESS COMPATIBLE":"! PROCESS INCOMPATIBLE"}</strong><span>{result.compatible?"The line can manufacture this die.":"Die dimensions, target tier, node, or transistor construction exceeds this line."}</span></div><section className="yield-grid"><article><p className="panel-label">POISSON YIELD</p><strong className="yield-big">{percent(result.yieldData.yield)}</strong><dl><div><dt>Critical area</dt><dd>{result.yieldData.criticalArea.toFixed(2)} mm²</dd></div><div><dt>Fill fraction</dt><dd>{percent(result.yieldData.fillFraction)}</dd></div><div><dt>Base D</dt><dd>{result.yieldData.baseDefectDensity.toFixed(5)}</dd></div><div><dt>Resolution pressure</dt><dd>{result.yieldData.resolutionPressure.toFixed(2)}×</dd></div><div><dt>Construction quality</dt><dd>{result.yieldData.constructionQuality.toFixed(2)}×</dd></div></dl></article><article><p className="panel-label">EXPECTED BINS</p><div className="bins">{Object.entries(result.probabilities).map(([label,value])=><div key={label}><span>{label}</span><i style={{width:percent(value)}}/><strong>{percent(value)}</strong></div>)}</div></article></section><section className="material-table"><div className="table-head"><span>STAGE</span><span>MATERIAL</span><span>EXPECTED USED</span><span>EXPECTED SAVED</span></div>{result.materials.map(item=><div key={item.stage}><strong>{item.stage}</strong><span>{item.material}</span><span>{percent(item.used)}</span><span>{percent(item.saved)}</span></div>)}</section></>}</main>;
}
